<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>keranjang</name>
   <tag></tag>
   <elementGuidId>d48137fc-513d-4e44-b4f4-710ab322df79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='shopping_cart_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value></value>
      <webElementGuid>fd44fef9-a89c-43c2-b89d-79dc9bc1b8d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
