<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>keranjang</name>
   <tag></tag>
   <elementGuidId>d48137fc-513d-4e44-b4f4-710ab322df79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//a[@class='shopping_cart_link']</value>
      <webElementGuid>c163854d-2286-4791-a0ac-00a8862c3451</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
